Tradução subtítulos
braziljs/eloquente-javascript pull request #446
Opened 2020-05-04 00:29 UTC by GSFZamai

Concluída a tradução dos subtítulos

2020-05-05 13:56 UTC, joaostein commented
Fala, @GSFZamai. Para facilitar a revisão do capítulo 02, vamos manter um único _pull request_. Basta continuar enviando as alterações por aqui que, após fazermos a tradução e revisão, fazemos o _squash_ e _merge_ em um único _commit_.

Quando  estiver pronto para revisão, poderia, por gentileza, me dar um ping avisando?

2020-05-05 14:38 UTC, GSFZamai commented
Bom dia, @joaostein, beleza!
Pode xiexar que mando sim, um abraço!

2020-05-14 12:36 UTC, GSFZamai commented
Bom dia, @joaostein  
Finalizada a tradução do capítulo, pronto para revisão.

2020-05-18 22:25 UTC, joaostein requested changes
valeu @GSFZamai! Adicionei alguns comentários de review.

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Se você remover a declaração `break` ou você acidentamente escreveu
acidentamente -> acidentalmente

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Se você crear um loop infinito em um dos exemplos nessas páginas,
crear -> criar
loop -> sempre em itálico

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +você normalmente será questionado se quer finalizar o script após alguns segundos.
script -> _script_ (itálico)

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
>  control jumps out of the body and continues with the loop's next
linha em inglês

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Especialmente quando ao usar um loop, o programa com frequência necessita "atualizar" a ligação
ao usar -> usar

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +JavaScript fornece um atalho para isso
isso -> isso.

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +para dobrar `result` ou `conter -= 1` para contar regressivamente.
`conter -= 1` -> `counter -= 1`

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +para dobrar `result` ou `conter -= 1` para contar regressivamente.
`conter -= 1` -> `counter -= 1`

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +## Enviando um valor com *switch*
usar `_` para itálico

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Não é incomum um código se parece com isso:
parece -> parecer

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Exsite uma construção chamada `switch` que tem a inteção de expressar
Exsite -> Existe
inteção -> intenção

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +o envio de uma forma mai direta. Infelizmente, a sintaxe que o JavaScritp usa para isso
mai -> mais
JavaScritp -> JavaScript

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +não deseja que exetcute.
exetcute -> execute

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Nomes de ligações não podem conter espaços, mesmo assim usar multiplas palavras
multiplas -> múltiplas

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Isso é claramente uma decisão sua nomear uma ligação com várias palarvas:
palarvas -> palavras

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +prefiro o visual dos underlines, embora esse estilo seja penoso para digitat.
underlines -> itálico
digitat -> digitar

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
>  underscores, though that style is a little painful to type. The
linha em inglês

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Isso é feito para marcar essa função como contrutora. O que é uma função construtora ficará mais claro no
contrutora -> construtora

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +comentários. Escrever um comentário se única linha, você pode usar dois carácteres de barra
Escrever um comentário se única linha -> Para escrever um comentário de linha única

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +(`//`) e então o texto de comentário após elas.
e então o texto -> e, então, o texto

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +expressões, os quais podem ser contruidos de expressões menores.
os quais -> as quais
contruidos -> construídas

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Colocar declarações após outra declaração the dá um programa que é
the -> lhe / te

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +executado do topo para baixo. Você pode introduzir alterações no clontrole de fluxo
clontrole -> controle

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +ao utilizar declarações condicionais (`if`, `else`, e `switch`) e loops (`while`, `do`, e `for`)
loops -> itálico

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Ligações podem ser usadas para arquivar pedaços de dados sob nome, e elas são
sob nome -> em um nome

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +que são definidas. Sistemas JavaScript sempre coloca um número de ligações padrões úteis
coloca -> colocam

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Se você deseja aprender algo dos exercícios, Eu recomendo consultar as soluções
Eu -> eu

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +### Triângulo com Loop
Loop -> itálico

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Pode ser útil saber que você pode descobrir o comprimento da string ao escrever
string -> itálico

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +A maioria dos exercícios contém um pedaço de código que você pode modificar para solucionar
contém -> contêm

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +o exercício. Lembre-se que você pode clicar os blocos e código e editá-los.
clicar os blocos e código -> clicar nos blocos de código

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +you can derive by making a few modifications to the [exemplo de impressão de números ímpares](program_structure#loops)
texto em inglês

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Agora considere a equivalência entre números e strings de caractéres de cerquilha.
strings -> itálico
caractéres -> caracteres

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +ao adicionar um caracter (`+= "#"`). Desse modo, sua solução pode estar
caracter -> caractere

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +significante de candidatos à programadores. Então se você resolvê-lo, seu valor no mercado de trabalho
Então se -> Então, se

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Exeminar os números é claramente um trabalho para um loop, e selecionar o que
Exeminar -> Examinar

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +operador resto (`%`) para checar se um número é divisivel por outro (possui um resto de zero).
divisivel -> divisível

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Você pode construir a _string_ ao iniciando por uma vazia (`""`) e
ao iniciando -> iniciando

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +repetidamente adicionando characters. Um caracter _newline_ é escrito com `"\n"`.
adicionando -> adicionar
characters -> caracteres

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Coloque chaves em volta do corpo de embos os loops para tornar fácil de identificar
embos -> ambos
loop -> itálico (sempre)

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +onde eles começam e terminam. Tente identar apropriadamente o corpo dos loops.
identar -> indentar

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +A ordem dos loops deve seguir a order que nós contruimos a _string_
contruimos -> construímos

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Então o loop externo cuida das linhas, e o loop interno cuida dos caractéres da linha.
caractéres -> caracteres

2020-05-18 22:25 UTC, joaostein commented on 02_program_structure.md
> +Terminando a linha ao adiconar um caracter _newline_ deve acontecer após a
caracter -> caractere

2020-05-19 14:31 UTC, GSFZamai reviewed
Bom dia @joaostein , revisado!

2020-06-23 14:43 UTC, joaostein requested changes
@GSFZamai segunda leva de revisão.

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Isso nos permite criar expressões que descrevem cálculos arbitráriamente complexos.
arbitráriamente -> arbitrariamente

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +As regras para quando for seguro omití-lo são de alguma forma complexas e passíveis de erro.
omití-lo -> omiti-lo

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +(_((paravra-chave))_) `let` indica que essa declaração irá definir
paravra-chave -> palavra-chave

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +ligações existentes para desconectá-las de seu valor atual e apontá-las
desconectá-las -> desconecta-las

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Quando você define uma ligação sem atribur um valor à ela, o tentáculo
atribur -> atribuir

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +se lembre que elas básicamente fazem a mesma coisa, mas nós raramente a usaremos nesse livro
básicamente -> basicamente

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +_underlines_ (`_`) mas nenhuma outra pontuação ou caractere especial.
_underlines_ -> _underscores_ (se está usando inglês, deixa como original)

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Não se preocupe em memorizar essa lista. Quando ao criar uma ligação poduzir o erro
poduzir -> produzir

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +((padrão)), e na marioria das vezes, ele também possui ligações que fornecem formas
marioria -> maioria

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +de interagir com o sistema que o cerca. Por exempo, em um navegador, existem funções para
exempo -> exemplo

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +interagir com o website ataualmente carregado e para ler as entradas do ((mouse)) e ((teclado)).
ataualmente -> atualmente

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Você pode chamar uma função ao colocar parentêses após a expressão que produz o valor da expressão.
parentêses -> parênteses

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +baseado na situação em que se encontra. Isso é chamado de _((execução condional))_.
condional -> condicional

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +expressão Booleana. A expressão decisiva é escrita após a palavra-chave, entre parentêses, seguida por
parentêses -> parênteses

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +é representado pela segunda flecha do diagrama. Você pode usar a palava-chave `else`, junto com `if`, para criar dois caminhos
palava-chave -> palavra-chave

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Se você possui mais que dois caminhos para escolher, você pode "encadear" múltiplos pares de`if`/`else` juntos.
de`if`/`else` -> de `if`/`else` (adicionar espaço)

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +com qual frequência nós temos que múltiplicar esse resultado por 2. O _loop_ testa
múltiplicar -> multiplicar

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +isso é mais curto e claro que a contrução `while`.
contrução -> construção

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +O primeiro estilo pode tornar díficil de ler. Eu particularmente
díficil -> difícil

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Não é dificil se acostumar com coisas pequenas como essa, e o código com estilos de nomes
dificil -> difícil

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +prefiro o visual dos _underlines_, embora esse estilo seja penoso para digitar.
_underlines_ -> _ underscores_

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +mistos podem se tornar duros de ser ler, então seguimos essa ((conveção)).
conveção -> convenção

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Você sabe agora que um programa é construido por declarações, as quais
construido -> construído

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +expressões, as quais podem ser costruídas de expressões menores.
costruídas -> construídas

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +A ordem dos loops deve seguir a order que nós contruímos a _string_
contruímos -> construímos
order -> ordem

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +(linha por lina, esquerda para direita, de cima para baixo).
lina -> linha

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +coloar um espaço ou uma cerquilha na posição dada, você poderia testar se a soma
coloar -> colocar

2020-06-23 14:43 UTC, joaostein commented on 02_program_structure.md
> +Terminando a linha ao adiconar um caractere _newline_ deve acontecer após a
adiconar -> adicionar

2020-07-24 09:50 UTC, GSFZamai reviewed
Revisão Concluída

2020-08-06 13:25 UTC, joaostein requested changes
@GSFZamai terceiro round de reviews

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +que um loop pode sinalizar. Existe uma declaração especial chamada `break` que possui
sinalizar -> finalizar

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Usando o operador resto (`%`) é uma forma fácil de testar se o número é
Usando -> Usar

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Se isso falhar, você terá que fechar a aba que você está trabalhando,
Se isso falhar, você terá que fechar a aba que você está trabalhando ou, em alguns navegadores, fechar todo o navegador para recomeçar.

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +é de alguma forma estranha -uma corrente de declarações `if` talvez
`-uma` -> `. Uma`

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +O programa irá iniciar a execução no rótulo que corresponde ao valor que foi dado ao `switch`,
irá iniciar -> iniciará

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +ou pelo `default` e nenhuma combinação de valores for encontrada. Ele irá continuar executando,
e nenhuma -> se nenhuma

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Mas cuidado-é fácil se esquecer de tal `break`, o que irá fazer o programa executar código que você
`Mas cuidado-` -> `Mas cuidado,`

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +O primeiro estilo pode tornar difícil de ler. Eu particularmente
`tornar difícil` -> `ser difícil`

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +seguem o último estilo-eles escrevem com a primeira letra maiúscula todas as palavras
As funções ((padrões)) JavaScript e a maior parte dos programadores JavaScript seguem o último estilo, escrevendo com a primeira letra maiúscula todas as palavras

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +[Capítulo ](object#constructors). Por enquanto, a coisa mais importante é não se incomodar
`[Capítulo ](object#constructors)` -> `[Capítulo ?](object#constructors)`

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Colocar declarações após outra declaração te dá um programa que é
`Colocar declarações após outra declaração` -> `Colocar declarações após as outras`

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +pode invocá-las ao escrever `functionName(argument1, argument2)`. Assim
`Assim` -> `Assim,`

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Você pode começar com um programa que imprima os números 1 à 7, que
1 à 7 -> 1 a 7

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Você pode ir de 1 à 2 ao adicionar ' (`+= 1`). Você pode ir de `"#"` para `"##"`
1 à 2 -> 1 a 2

2020-08-06 13:25 UTC, joaostein commented on 02_program_structure.md
> +Escreva um programa que usa `console.log` para imprimir todos os números de 1 à 100,
1 à 100 -> 1 a 100

2020-09-10 15:54 UTC, GSFZamai reviewed
Correções finalizadas

2020-09-17 12:58 UTC, joaostein requested changes
Quarta leva de reviews. Acho que depois dessa provavelmente estará pronto para merge.

2020-09-17 12:58 UTC, joaostein commented on 02_program_structure.md
> +As declarações no exemplo anterior apenas produzem os valores `1` e `true` e, então, imediatamente, os joga fora.
imediatamente, -> imediatamente

2020-09-17 12:58 UTC, joaostein commented on 02_program_structure.md
> +Elas não _contêm_ valores, elas _pegam_ eles, duas ligações podem se referir ao
`, duas ligações podem se referir ao mesmo valor.` -> 
`(duas ligações podem se referir ao mesmo valor).`

colocar entre parênteses ou colocar em uma nova frase.

2020-09-17 12:58 UTC, joaostein commented on 02_program_structure.md
> +ele escolherá essa ramificação, mostre "Small" e pronto. Se não for,
mostre "Small" -> mostrando `` `"Small"` ``

2020-09-17 12:58 UTC, joaostein commented on 02_program_structure.md
> +condição (`< 100`) for satisfeita, isso significa que o número está entre 10 e 100, e "Medium" é exibido.
`100, e` -> `100 e`
"Medium" -> `` `"Medium"` ``

2020-09-17 12:58 UTC, joaostein commented on 02_program_structure.md
> +quatro espaços, e outras usam o ((caractere tab)). O mais importante é que cada novo bloco adicione
`espaços, e outras` - > `espaços e outras`

2020-09-17 12:58 UTC, joaostein commented on 02_program_structure.md
> +ou pelo `default` se nenhuma combinação de valores for encontrada. Ele irá continuar executando,
irá continuar -> continuará

2020-11-06 15:13 UTC, merged

2020-11-06 15:13 UTC, joaostein commented
Valeu, @GSFZamai 🎉