docs: translate introduction cap4
braziljs/eloquente-javascript pull request #453
Opened 2020-08-19 03:12 UTC by cristofersousa

## Motivo
Conforme orientado é apenas um PR com a tradução completa do capítulo.
Como será feito squash depois, estou abrindo um commit por sessão  do capítulo 4.

##  Seções traduzidas

- [x] Introdução
- [ ] The weresquirrel 
- [ ] Data sets
- [ ] Properties
- [ ] Methods
- [ ] Objects
- [ ] Mutability
- [ ] The lycanthrope’s log
- [ ] Computing correlation
- [ ] Array loops
- [ ] The final analysis
- [ ] Further arrayology
- [ ] Strings and their properties
- [ ] Rest parameters
- [ ] The Math object
- [ ] Destructuring
- [ ] JSON
- [ ] Summary
- [ ] Exercises

2020-08-20 22:47 UTC, cristofersousa commented
@joaostein  pode dar um look?

2020-08-20 23:10 UTC, joaostein requested changes
@cristofersousa segue as primeiras sugestões de melhoria para você ter uma direção mais clara. Sobre os reviews, assim que tiver traduzido o capítulo inteiro (todas as 19 seções que você pontuou), é só me avisar que, assim que possível, revisarei o seu trabalho.

2020-08-20 23:10 UTC, joaostein commented on 04_data.md
> +Números, Booleans e Strings são como os átomos(dados). Muitos tipos de informações requerem mais de um átomo, no entanto. _Objects_ nos permitem agrupar valores - incluindo outros objetos que nos for
`Booleans` -> `_Booleans_`
`Strings` -> `_Strings`

`são como os átomos(dados)` -> `são como os átomos nos quais as estruturas de ((dados)) são construídas`

`agrupar valores - incluindo outros objetos que` -> `agrupar valores, incluindo outros objetos, que`

`complexas..` -> `complexas.`

2020-08-20 23:10 UTC, joaostein commented on 04_data.md
> +Os programas que contruímos até agora foram limitados pelo fato de estavámos operando apenas tipos de dados mais simples. Este capítulo vai introduzir estrutura de dados básicas. Ao final, você saver
`contruímos` -> `construímos`
`fato de estavámos` -> `fato de que estávamos`
`saverá` -> `saberá`

2020-08-20 23:10 UTC, joaostein commented on 04_data.md
> +Caso queira fazer a codifição dos exemplos desse livro na guia sandbox
`sandbox` -> `((sandbox))`

2020-08-20 23:10 UTC, joaostein commented on 04_data.md
> +você terá uma forma de executar o código a partir do contexto de um capítulo espécifico. E se você decidir trabalhar com os exemplos em outro ambiente de desenvolvimento, certifique-se primeiro de fa
`E se você decidir` -> `Se você decidir` / `Caso você decida`
`sandbox` -> `_sandbox_`

2026-05-13 12:31 UTC, joaostein commented
Oi, valeu pela contribuição. A tradução da 3ª edição não foi concluída e estamos pulando direto pra 4ª (#490), então essa branch fica como histórico. Fechando aqui — se quiser ajudar a revisar a 4ª edição, é só pular no #490.

2026-05-13 12:31 UTC, closed without merging