Tradução do capítulo 3
braziljs/eloquente-javascript pull request #456
Opened 2020-09-04 21:06 UTC by raphaelkieling

Irei manter centralizado aqui o meu trabalho de tradução no meu tempo livre. Logo logo irei atualizar com meu todos.

2022-04-15 20:47 UTC, raphaelkieling commented
@joaostein finalizado. Vou passar o olho novamente pra ver se acho alguma incongruência.

2022-11-14 09:42 UTC, joaostein requested changes
fala @raphaelkieling adicionei algumas revisões

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +O conjunto de variáveis visíveis dentro de um bloco é determinado pelo local onde o bloco está no texto do programa. Cada escopo local pode também ver todo os escopos locais que à contem, e todos os
Deste -> Desta

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Isto é uma declaração de função. Ela define a variável `squase` e aponta para a função dada. É um pouco mais fácil para escrever e não requer um ponto e vírgula após a função.
`squase` -> `square`

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +O exemplo acima funciona, mesmo sabendo que a função foi definida *após* o código que a executa. Isso ocorre porque as declarações de funções não fazem parte do fluxo normal de controle, que é execut
`*` para `_`

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Há uma terceira forma de declaras funções chamada `Arrow function` (Função de seta), no qual parece bem diferente das outras. Ao invés de usar a chave `function`, isto usa uma flecha `=>` composto po
trocar os ticks em `Arrow function` para `_`. Ticks são usados para trechos de código.

Estrangeirismo é marcado com `_`. (veja [boas práticas](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md#boas-pr%C3%A1ticas))

declaras -> declarar
Há uma terceira forma de declarar funções -> adicionar vírgula após funções
no qual -> que parece
chave -> palavra-chave
composto -> composta

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Não há nenhuma razão profunda para ter funções de seta e expressões utilizando a chave `function` na linguagem. Além de um pequeno detalhe, no qual vamos discutir no [Capítulo ?](object), eles fazem
chave -> palavra-chave

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Nós definimos `squase` com apenas um argumento. No entando, quando ela é chamada com três, a linguagem não reclama. É ignorado os argumentos adicionais e executa a função `square` apenas com o primei
`squase` -> `square`
entando -> entanto

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
>  The upside is that this behavior can be used to allow a function to be
remover bloco duplicado em inglês do texto original

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +A vantagem é que esse comportamento pode ser usado em funções que aceitam argumentos opcionais. Por exemplo, esta função `minus` tenta imitar o operador `-` executando com 1 ou menos argumentos.
com 1 ou menos -> com um ou dois

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Se você escreve um operador `=` depois de um parâmetro, seguindo de uma expressão, o valor da expressão vai substituir o argumento quando não é definido.
seguindo -> seguido

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +É perfeitamente aceitável uma função invocar a si mesma, contanto que se tenha cuidado para não sobrecarregar a pilha de chamadas. Uma função que invoca a si mesma é denominada *recursiva*. A recursi
`*` para `_`

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Portando, sempre comece escrevendo algo que é correto e fácil de entender. Se você está preocupado que isso é muito lento - o que geralmente não é, já que a maioria dos códigos simplesmente não é exe
Portando -> Portanto

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +A recursão nem sempre é apenas uma alternativa ineficiente ao loop. Alguns problemas são realmente mais fáceis de resolver com recursão do que com loops. Na maioria das vezes, esses são problemas que
loop -> adicionar `_`

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
>  from this number, it returns `null`.
remover bloco original em inglês

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +A identação indica a profundidade da pilha de chamadas. A primeira vez que `find` é chamado, ele começa chamando a si mesmo para explorar a solução que começa com `(1 + 5)`. Essa chamada recorrerá ai
identação -> indentação

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
>  actually define the function itself.
remover bloco de código em inglês

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Queremos escrever um programa que imprima dois números: os números de vacas e galinhas em uma fazenda, com as palavras 'Cows' e 'Chickens' depois deles e zeros preenchidos antes de ambos os números p
'Cows' e 'Chickens' -> `Cows` (vacas) e `Chickens` (galinhas) 

usar tick e adicionar tradução em parênteses

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Uma função com um nome bonito e óbvio como `zeroPad` torna mais fácil para alguém que lê o código descobrir o que ele faz. E tal função é útil em mais situações do que apenas neste programa específic
usá-lo -> usá-la

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Esse capítulo te ensinou voçê como escrever suas próprias funções. A palavra chave `function`, quando usada como uma expressão, pode criar uma função de valor. Quando usada como declaração, pode ser
te ensinou voçê -> ensinou você ou te ensinou
palavra chave -> palavra-chave
`_`em Arrow functions (estrangeirismo)

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +// Defina f para manter o valor de uma funcão
não traduzir blocos de código

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +// Declare g para ser uma funcão
não traduzir blocos de código

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +// Uma funcão de valor menos verbosa
não traduzir blocos de código

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +Um aspecto chave para entender funções, é entender os escopos. Cada bloco cria um novo escopo. Parâmetros e variáveis declarados em um determinado escopo são locais e não são visíveis de fora. Variáv
entender funções, é entender os escopos -> tirar vírgula
craidas -> criadas

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +// Seu código aqui.
não traduzir bloco de código

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +// Seu código aqui.
não traduzir bloco de código

2022-11-14 09:42 UTC, joaostein commented on 03_functions.md
> +// Seu código aqui.
não traduzir bloco de código

2022-11-20 16:11 UTC, raphaelkieling commented on 03_functions.md
> +Funções são o pão e manteira da programação JavaScript. O conceito deencapsular um pedaço de um programa em um valor tem muitos usos. Issonôs dá um caminho para estruturas grandes programas, reduzir
Vou alterar também:
Funções são o pão e **manteira** -> Funções são o pão e **manteiga**

2022-11-20 16:26 UTC, raphaelkieling commented on 03_functions.md
> +O exemplo acima funciona, mesmo sabendo que a função foi definida *após* o código que a executa. Isso ocorre porque as declarações de funções não fazem parte do fluxo normal de controle, que é execut
![Screen Shot 2022-11-20 at 13 25 40](https://user-images.githubusercontent.com/16259523/202913608-332288e3-3a99-4523-959b-bf991631f51e.png)

Por algum motivo os `_` estão virando `*` no PR. Tem ideia do que pode ser?

2022-11-20 16:28 UTC, raphaelkieling commented on 03_functions.md
> +É perfeitamente aceitável uma função invocar a si mesma, contanto que se tenha cuidado para não sobrecarregar a pilha de chamadas. Uma função que invoca a si mesma é denominada *recursiva*. A recursi
![Screen Shot 2022-11-20 at 13 28 15](https://user-images.githubusercontent.com/16259523/202913699-b5b20407-663e-44bc-a66c-9958ec8ca7a7.png)

Mesma coisa, está correto pra mim mas no PR mostra `*`

2026-05-13 12:31 UTC, joaostein commented
Oi, valeu pela contribuição. A tradução da 3ª edição não foi concluída e estamos pulando direto pra 4ª (#490), então essa branch fica como histórico. Fechando aqui — se quiser ajudar a revisar a 4ª edição, é só pular no #490.

2026-05-13 12:31 UTC, closed without merging