Tradução capítulo 11
braziljs/eloquente-javascript pull request #462
Opened 2021-02-06 23:09 UTC by ggarber42

2021-02-14 20:24 UTC, joaostein requested changes
@ggarber42 - Obrigado pelo envio. 

Deixei o primeiro review com alguns ajustes finos.

Reparei que você criou um novo arquivo diferente do original (`11_async.md`). Além disso, adicionou e editou outros elementos do repositório. Apenas para sua referência, vamos manter a estrutura de arquivos do livro original para esta versão.

Por isso, gostaria de solicitar que, além da tradução do conteúdo em texto, mantenha a estrutura original dos arquivos sem as alterações/adaptações que você adicionou.

Assim que as mudanças forem aplicadas, farei um segundo review. Enquanto isso, se precisar de qualquer coisa, é só me avisar.

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Mas para tornar esses ninhos capazes de receber essa _request_, nós primeiro precisamos definir uma _request_ chamada “`note`”. O código que vai tratar com _requests_ precisa ser executado não apenas
`vôe` -> `voe`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +O quarto argumento dado ao tratador, `done`, é a função de _callback_ que precisa ser chamada quando a _request_ termina. Se tivéssemos utilizado o retorno do tratador como resposta, isso iria signif
`terminar,tendo` -> `terminar, tendo`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Para criar uma _promise_, pode-se utilizar `Promise` como um construtor. Ele possui uma interface peculiar — o construtor espera uma função como argumento, que é chamada imediatamente, passando uma f
método``resolve`` -> método ``resolve``

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Quando um vizinho não está disponível, nós não queremos que o conjunto de todas as  _promises_ fracasse, já que assim ainda não saberiamos de nada. Então, a função que é mapeada em cima do conjunto d
`saberiamos` -> `saberíamos`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Quando um vizinho não está disponível, nós não queremos que o conjunto de todas as  _promises_ fracasse, já que assim ainda não saberiamos de nada. Então, a função que é mapeada em cima do conjunto d
`vínculadas` -> `vinculadas`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Para evitar enviar a mesma mensagem pela rede para sempre, cada ninho possui um _array_ de _strings_ de fofocas que já foram enviadas. Para definir esse _array_, nós utilizamos a função `everywhere`,
`ojeto` -> `objeto`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +A comparação utiliza `JSON.stringify` porque ==, em objetos ou _arrays_, irá retornar verdadeiro apenas quando os dois são exatamente o mesmo valor, o que não precisamos. Compar as _strings_ de JSON
`Compar` -> `Comparar`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Algo que é possível fazer com diagramas é encontrar as rotas, como vimos no capítuolo 7[]. Se nós tivermos a rota para o destino da mensagem, nós sabemos para qual direção enviar.
`capítuolo` -> `capítulo`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Até para _promises_ esse código é esquisito. Múltiplas ações assíncronos estão encadeadas de manerias não óbvias. Nós precisamos novamente de uma função recursiva (``` next ```) para modelar o _loopi
`manerias` -> `maneiras`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +A boa notícia é que o JavaScript permite que você escreva código pseudo-síncrono para descrever computação assíncrona. A função `async` é uma função que implicitamente retorna uma _promise_ que pode,
`dentro de sí` -> `dentro de si`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +O código não parece imediatamente suspeito...ele mapeia a função flecha `async` através de um conjunto de ninhos, criando um _array_ de _promises_ e utiliza o `Promise.all` para esperar por todas aqu
`contruíram` -> `construíram`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Programação assíncrona torna possível expressar esperas por ações que rodam por muito tempo sem congelar o programa durante essas ações. Ambientes JavaScript tipicamente implementam esse estilo de pr
`uitilizando` -> `utilizando`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Programando assíncronamente se torna mais fácil com _promises_, objetos que representam ações que pode ser completas no futuro e funções `async`, que permitem que você escreva um progama assíncrono c
`progama` -> `programa`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Para fazer o mesmo numa função normal, você vai ter que construir o _loop_ utilizando uma funçãor recursiva. A maneira mais fácil de fazer isso é ter a função retornando uma  _promise_ chamando `then
`funçãor` -> `função`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Para fazer o mesmo numa função normal, você vai ter que construir o _loop_ utilizando uma funçãor recursiva. A maneira mais fácil de fazer isso é ter a função retornando uma  _promise_ chamando `then
`armazendo` -> `armazenado`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Na função `async`, _promises_ rejeitadas são covertidas por exeções pelo `await`. Quando a função `async` joga uma exeção, a _promise_ é rejeitada. Assim funciona.
`covertidas` -> `convertidas`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Na função `async`, _promises_ rejeitadas são covertidas por exeções pelo `await`. Quando a função `async` joga uma exeção, a _promise_ é rejeitada. Assim funciona.
`exeções` -> `exceções`
`exeção` -> `exceção`

2021-02-14 20:24 UTC, joaostein commented on chapters/11-programacao-assincrona.md
> +Lembrando que depois da  _promise_ ter sucesso ou falhar, ela não pode ter sucesso ou fracassar novamente, em próximas chamadas para funções que as resolvem são ignoradas. Isso pode simplificar a for
`da sua  _promise_` -> `da sua _promise_`

2021-02-17 23:48 UTC, ggarber42 commented
Beleza, no fds eu vou dar um revisada sim.

2021-02-27 11:56 UTC, ggarber42 commented
Bom dia @joaostein tudo certo?

Então eu alterei o nome dos outros arquivos porque não encontrei o arquivo **11_async.md** 

![Screenshot from 2021-02-27 08-50-10](https://user-images.githubusercontent.com/26423380/109386343-d4007180-78d8-11eb-8f0e-5ecf5d128215.png)

Aí eu tentei renomear os arquivos, para ter a ordem certa (pois já existe um capítulo 11 atualmente). 

Mas, no caso o que eu preciso fazer é  criar esse arquivo **11_async.md** para a tradução? Que depois vocês arrumam o resto da estrutura?

Só fiquei com essa dúvida, valeu!!!

2021-02-27 15:00 UTC, joaostein commented
@ggarber42 você está utilizando os arquivos do branch `master` (segunda versão do livro). Para acessar os arquivos da terceira versão, que é a que estamos trabalhando, você deverá usar o branch `3rd`.

https://github.com/braziljs/eloquente-javascript/tree/3rd

2021-04-25 20:59 UTC, closed without merging

2021-04-25 21:00 UTC, ggarber42 commented
@joaostein  vou abrir outra PR com a branch correta. Mas eu fiz as modificações da tua revisão.