Tradução capítulo 11
braziljs/eloquente-javascript pull request #465
Opened 2021-05-08 20:57 UTC by ggarber42

@joaostein coloquei a pull pra versão 3 e mantive as modificações indicadas da  [PR](https://github.com/braziljs/eloquente-javascript/pull/462).

Verifica se agora a estrutura está de acordo e qualquer coisa me avisa.

2021-06-05 15:20 UTC, joaostein requested changes
@ggarber42 segunda leva de reviews. alguns _typos_. #410

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Quem pode permancer parado até o momento de agir?
permancer -> permanecer

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +O quarto argumento dado ao tratador, `done`, é a função de _callback_ que precisa ser chamada quando a _request_ termina. Se tivéssemos utilizado o retorno do tratador como resposta, isso iria signif
terminar,tendo -> terminar, tendo

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +É útil pensar em _promises_ como dispositivos para transportar o valor em uma realidade assíncrona. Um valor normal simplesmente está aqui. Um valor prometido é um valor que **pode** já estar aqui ou
assíncronamente -> assincronamente

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Para criar uma _promise_, pode-se utilizar `Promise` como um construtor. Ele possui uma interface peculiar — o construtor espera uma função como argumento, que é chamada imediatamente, passando uma f
método`resolve` -> método `resolve`

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Para construir um _loop_ assíncrono, para múltiplas tentativas, nós precisamos utilizar uma função recursiva — um _loop_ convencional não permite que nós esperemos a respostas de uma ação assíncrona.
instânica -> instância

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Quando um vizinho não está disponível, nós não queremos que o conjunto de todas as  _promises_ fracasse, já que assim ainda não saberiamos de nada. Então, a função que é mapeada em cima do conjunto d
saberiamos -> saberíamos
vínculadas -> vinculadas

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Para evitar enviar a mesma mensagem pela rede para sempre, cada ninho possui um _array_ de _strings_ de fofocas que já foram enviadas. Para definir esse _array_, nós utilizamos a função `everywhere`,
ojeto -> objeto

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +A comparação utiliza `JSON.stringify` porque ==, em objetos ou _arrays_, irá retornar verdadeiro apenas quando os dois são exatamente o mesmo valor, o que não precisamos. Compar as _strings_ de JSON
Compar -> Comparar

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Até para _promises_ esse código é esquisito. Múltiplas ações assíncronos estão encadeadas de manerias não óbvias. Nós precisamos novamente de uma função recursiva (``` next ```) para modelar o _loopi
manerias -> maneiras

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +A boa notícia é que o JavaScript permite que você escreva código pseudo-síncrono para descrever computação assíncrona. A função `async` é uma função que implicitamente retorna uma _promise_ que pode,
dentro de sí -> dentro de si

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +O código não parece imediatamente suspeito...ele mapeia a função flecha `async` através de um conjunto de ninhos, criando um _array_ de _promises_ e utiliza o `Promise.all` para esperar por todas aqu
contruíram -> construíram

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Programação assíncrona torna possível expressar esperas por ações que rodam por muito tempo sem congelar o programa durante essas ações. Ambientes JavaScript tipicamente implementam esse estilo de pr
uitilizando -> utilizando

2021-06-05 15:20 UTC, joaostein commented on 11_async.md
> +Programando assíncronamente se torna mais fácil com _promises_, objetos que representam ações que pode ser completas no futuro e funções `async`, que permitem que você escreva um progama assíncrono c
assíncronamente -> assincronamente
progama -> programa

2021-08-14 21:23 UTC, joaostein requested changes
Seguem algumas indicações para ajustes. Lembre-se de verificar os espaços duplos (muitas ocorrências) e os ` `` `.

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Cada ninho computador mantêm uma lista de outros ninhos com os quais pode se comunicar em sua propriedade `neighbors`. Para verificar quais estão disponíveis, você pode escrever uma função que tenta
`ping` as aspas ficam dentro do ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +A comparação utiliza `JSON.stringify` porque ==, em objetos ou _arrays_, irá retornar verdadeiro apenas quando os dois são exatamente o mesmo valor, o que não precisamos. Compar as _strings_ de JSON
`==` faltou ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +[Chapter 7](robot). Se nós tivermos a rota para o destino da mensagem, nós sabemos para qual direção enviar.
`Chapter 7` -> `Chapter ?` (pode deixar igual o original)

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +A função `findRoute`, que lembra bastante a `findRoute` do [Chapter 7](robot#findRoute), procura uma forma de alcançar um nó da rede. Mas, ao invés de retornar toda a rota, retorna apenas o próximo p
mesma coisa aqui `Chapter 7` -> `Chapter ?`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Agora nós podemos construir uma função que envia mensagem de distâncias longas. Se a mensagem for endereçada a um vizinho próximo, ela retorna como de costume. Se não, ela é empacotada em um objeto e
`route` as aspas ficam dentro do ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Porque `connections` é um `Map`, `Object.keys` não funciona nele. Se possui um **método** `keys`, mas retorna um iterador  ao invés de um _array_). O iterador (ou o valor iterável) pode ser convertid
`iterador ao invés` -> remover espaço extra

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Até para _promises_ esse código é esquisito. Múltiplas ações assíncronos estão encadeadas de maneiras não óbvias. Nós precisamos novamente de uma função recursiva (``` next ```) para modelar o _loopi
`next` só precisa de um ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Tal função não mais, como numa função Javascript padrão, roda do começo ao fim de uma vez. Ao invés disso, ela fica congelada no ponto que possui o `await` e pode ser retomada depois.
`Javascript` -> `JavaScript`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Quando você define uma função com `function*` (colocando um asterisco depois da palavra `function`), ela se torna um _generator_. Quando você chama um _generator_, ele retorna um iterador, o qual já
`Chapter 6` -> `Chapter ?`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Inicialmente, quando você chama `powers`, a função é congelada quando começa. Cada vez que você chama  `next`  no iterador, a função roda até que chega na expressão `yields`, que a pausa e faz com qu
`você chama next no iterador` -> remover espaços

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Inicialmente, quando você chama `powers`, a função é congelada quando começa. Cada vez que você chama  `next`  no iterador, a função roda até que chega na expressão `yields`, que a pausa e faz com qu
`( a do exemplo` -> `(a do exemplo` (remove espaço)

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Escrever iteradores é geralmente muito mais simples quando se utiliza funções geradoras. O iterador para a classe `Group` (do exercício do [Chapter 6](object#group_iterator))pode ser escrita com o ge
`Chapter 6` -> `Chapter ?`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Escrever iteradores é geralmente muito mais simples quando se utiliza funções geradoras. O iterador para a classe `Group` (do exercício do [Chapter 6](object#group_iterator))pode ser escrita com o ge
`))pode` -> `)) pode`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Comportamento assíncrono acontece na sua _stack_ de chamada de função vazia. Esta é uma das razões pelas quais, sem _promises_, controlar as exceções em um código assíncrono é difícil. Já que cada _c
`catch` precisa apenas de um ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Não importa o quão próximos os eventos — como os _timeouts_ ou _requests_ — ocorrem, um ambiente JavaScript sempre vai rodar apenas um programa de cada vez. Você pode pensar nisso como se ele estives
`eventos.s.` -> `eventos.`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +A parte `async name =>`  mostra que funções em flecha também podem se tornar `async` ao colocar a palavra `async` na frente delas.
`async name => mostra` -> remover espaço adicional

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Mas entre o tempo em que a declaração começa a ser executada e o hora em que ela termina há uma lacuna assíncrona. A expressão `map` roda antes que qualquer coisa seja adicionada a lista, então o ope
faltou ` `` ` no `+=`

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Erros assim são fáceis de cometer, especialmente quando utilizamos `await`, e você deve ficar atento de onde essas lacunas podem ocorrer. Uma vantagem a assincronicidade explícita do JavaScript (atra
`await` precisa apenas de um ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +A vila de corvos tem um velho bisturi que eles de vez em quando usam em missões especiais — por exemplo, para cortar telas de portas ou mochilas. Para poder rastreá-lo rapidamente, toda vez que o bis
`scapel` aspas é dentro do ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Escreva uma função assíncrona (`async`) `locateScalpel` que começando no ninho em que é executada. Você pode usar a função `anyStorage` definida anteriormente par acessar a memória de ninhos arbitrár
`scalpel` aspas é dentro do ` `` `

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Para fazer o mesmo numa função normal, você vai ter que construir o _loop_ utilizando uma função recursiva. A maneira mais fácil de fazer isso é ter a função retornando uma  _promise_ chamando `then`
`uma _promise_` -> remover espaço adicional

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Dado um _array_ de _promises_, `Promise.all` retorna uma _promise_ que espera que todas as  _promises_ do _array_ terminarem. Se é bem sucedida, gera um _array_ dos valores dos resultados. Se uma  _p
arrumar os espaços adicionais

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Lembrando que depois da  _promise_ ter sucesso ou falhar, ela não pode ter sucesso ou fracassar novamente, em próximas chamadas para funções que as resolvem são ignoradas. Isso pode simplificar a for
`depois da _promise_` -> remover espaço adicional

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +A função para o construtor da  `Promise` vai ter que chamar o `then` de cada _promise_ no dado _array_. Quando uma for bem sucedida, duas coisas precisam acontecer. O valor resultando precisa ser arm
`construtor da Promise` -> remover espaço adicional

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +A última pode ser feita com um contador  que é inicializado com o comprimento do _array_ de entrada e do qual nós subtraímos 1 cada vez que a _promise_ é bem sucedida. Quando atinge 0, nós terminamos
`com um contador que é` -> remover espaço adicional

2021-08-14 21:23 UTC, joaostein commented on 11_async.md
> +Ambas as plataformas de programação importantes de Javascript — navegador (_browser_) e  Node.js — fazem operações que podem ser assíncronas, ao invés de utilizarem fios. E como programação com fios
`Javascript` -> `JavaScript`

2021-10-02 11:28 UTC, ggarber42 commented
Acredito que foi tudo e desculpa a demora.

2021-11-20 11:20 UTC, joaostein requested changes
Faltaram diversos itens do review anterior. Poderia, por gentileza, olhar com atenção cada um dos comentários e fazer as correções?

2021-11-20 11:20 UTC, joaostein commented on 11_async.md
> +{{dica:
deixar como original `{{hint` ao invés de traduzir para `{{dica`

2021-11-20 11:20 UTC, joaostein commented on 11_async.md
> +{{dica:
deixar como original `{{hint` ao invés de traduzir para `{{dica`

2026-05-13 12:31 UTC, joaostein commented
Oi, valeu pela contribuição. A tradução da 3ª edição não foi concluída e estamos pulando direto pra 4ª (#490), então essa branch fica como histórico. Fechando aqui — se quiser ajudar a revisar a 4ª edição, é só pular no #490.

2026-05-13 12:31 UTC, closed without merging