Tradução Capítulo 9
braziljs/eloquente-javascript pull request #468
Opened 2021-07-14 22:20 UTC by bilianesilva

Finalizada a alteracao para o branch correto da 3rd.

2021-07-14 23:28 UTC, joaostein requested changes
@bilianesilva -- primeira revisão iniciada com alguns itens.

2021-07-14 23:28 UTC, joaostein commented on 09_regexp.md
> -{{quote {author: "Jamie Zawinski", chapter: true}
Reparei que você removeu do arquivo todos os metadados (tudo que está entre `{{}}`). Você poderia, por gentileza, manter a estrutura do arquivo original, sem remover essas informações?

2021-07-14 23:28 UTC, joaostein commented on 09_regexp.md
> -console.log(/[0-9]/.test("in 1992"));
blocos de código não são traduzidos.
(se precisar, revise o [guia de contribuição](https://github.com/braziljs/eloquente-javascript/blob/master/CONTRIBUTING.md#boas-pr%C3%A1ticas))

2021-07-15 00:15 UTC, bilianesilva commented on 09_regexp.md
> -{{quote {author: "Jamie Zawinski", chapter: true}
Eu acredito que tenha sido a minha extensão que uso no VScode. Vou dar uma olhada e consertar.

2021-07-15 16:14 UTC, bilianesilva commented on 09_regexp.md
> -{{quote {author: "Jamie Zawinski", chapter: true}
@joaostein eu preciso traduzir as palavras dos metadados (tudo que está entre {{}}), ou deixo em inglês?

2021-07-15 18:43 UTC, bilianesilva commented on 09_regexp.md
> -console.log(/[0-9]/.test("in 1992"));
Corrigido :)

2021-08-14 20:34 UTC, joaostein requested changes
@bilianesilva deixei alguns comentários para ajuste. Lembre-se de que estamos apenas traduzindo o conteúdo e queremos manter a estrutura o máximo possível igual ao arquivo original. Isso inclui os blocos de códigos também. Qualquer coisa só mandar mensagem que vamos conversando.

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +> "Algumas pessoas, quando confrontadas com um problema, pensam "Eu sei, terei que usar expressões regulares." Agora elas têm dois problemas.
Remover `>`

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +> "Yuan-Ma disse, 'Quando você serra contra o sentido da madeira, muita força será necessária. Quando você programa contra o sentido do problema, muito código será necessário'
Remover `>`

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +```js
remover `js`

Isso acontece em todos os blocos de código. Vamos manter o máximo possível igual o original.

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +    - \d	caracteres numéricos
você removeu as `|`, os ` `` ` e alterou o espaçamento. Vamos manter a estrutura igual o original, apenas traduza os textos.

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +{{index "plus character", repetition, `+ operator`}}
Manter como o original, você trocou aspas pelo `

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	let [_, month, day, year] = /(\d{1,2})-(\d{1,2})-(\d{4})/.exec(string);
mantenha o bloco de código como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +{{figure {url: "img/re_pigchickens.svg", alt: "Visualization of /\b\d+ (pig|cow|chicken)s?\b/"}}}
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +{{figure {url: "img/re_number.svg", alt: "Visualization of /\b([01]+b|\d+|[\da-f]+h)\b/"}}}
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	"Liskov, Barbara\nMcCarthy, John\nWadler, Philip".replace(
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	amount = Number(amount) - 1;
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	return code.replace(/\/\/.*|\/\*[^]*\*\//g, "");
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	return code.replace(/\/\/.*|\/\*[\w\W]*?\*\//g, "");
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +```js
lembre-se de remover o `js` de todos

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +while ((match = number.exec(input))) {
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +    /abc/	Sequência de caracteres
mantenha como o original. `|`, ` `` `, etc. Traduza apenas o texto

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +    1. "car" e "cat"
mantenha os itálicos com `_`

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +verify(/.../, ["my car", "bad cats"], ["camper", "high art"]);
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	["Siebentausenddreihundertzweiundzwanzig"],
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	["red platypus", "wobbling nest"],
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +	for (let str of yes)
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +for (let str of [
mantenha como o original

2021-08-14 20:34 UTC, joaostein commented on 09_regexp.md
> +for (let str of ["1a", "+-1", "1.2.3", "1+1", "1e4.5", ".5.", "1f5", "."]) {
mantenha como o original

2026-05-13 12:31 UTC, joaostein commented
Oi, valeu pela contribuição. A tradução da 3ª edição não foi concluída e estamos pulando direto pra 4ª (#490), então essa branch fica como histórico. Fechando aqui — se quiser ajudar a revisar a 4ª edição, é só pular no #490.

2026-05-13 12:31 UTC, closed without merging