Adiciona tradução da introdução
braziljs/eloquente-javascript pull request #473
Opened 2022-02-25 07:09 UTC by MarcusDavanco

2022-02-26 17:16 UTC, joaostein requested changes
obrigado pela contribuição, @MarcusDavanco. Deixei a primeira leva de review com alguns typos e detalhes a serem corrigidos.

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +`console.log`será usada para escrever o resultado.
`console.log`será -> adicionar espaço

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +linguagem de scripting e de consulta. Diversas plataformas para programação
`scripting` -> itálico

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +contém bastante coisas sobre código. Eu acredito que ler código e esscrever
`esscrever` -> `escrever`

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +Isto pode ser lento e confuso no começo, mas eu prometo que você rápidamente vai
`rápidamente` -> `rapidamente`

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +geramente escrito para embientes específicos (o navegador ou Node.js) e só pode
`geramente` -> `geralmente`
`embientes` -> `ambientes`

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +sem recarregar a página para cada ação. Javascript é também usado em websites
`Javascript` -> `JavaScript`

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +softwares que alegavam suporte a Javascript estavam realmente falando sobre a
`Javascript` -> `JavaScript`

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +Javascript. Os próximos sete capítulos são sobre ((navegadores)) web e a forma
`Javascript` -> `JavaScript`

2022-02-26 17:16 UTC, joaostein commented on 00_intro.md
> +que o Javascript tem acesso no navegador. Você aprenderá a exibir coisas na tela
`Javascript` -> `JavaScript`

2022-03-11 23:11 UTC, MarcusDavanco commented
@joaostein Implementadas as correções solicitadas

2022-10-08 18:15 UTC, MarcusDavanco commented
@joaostein Eu subi as correções apontadas já há algum tempo, mas não obtive resposta, o projeto ainda está ativo?

2023-07-08 10:33 UTC, closed without merging